schemaVersion: 2.2.0
metadata:
  name: core-docker-devs

components:
  - name: devtools
    container:
      env:
        - name: KUBEDOCK_ENABLED
          value: 'true'

        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'

        - name: TESTCONTAINERS_RYUK_DISABLED
          value: 'true'

        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: 'true'

      image: quay.io/devfile/universal-developer-image:latest

      memoryRequest: 2Gi
      memoryLimit: 8Gi
      cpuRequest: 300m

      cpuLimit: 4000m
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475 