schemaVersion: 2.2.0
metadata:
  name: core-docker-devs

components:
  - name: devtools
    container:
      env:
        - name: KUBEDOCK_ENABLED
          value: 'true'

        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'

        - name: TESTCONTAINERS_RYUK_DISABLED
          value: 'true'

        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: 'true'

      image: quay.io/devfile/universal-developer-image:latest

      memoryRequest: 2Gi
      memoryLimit: 16Gi
      cpuRequest: 4000m
      cpuLimit: 8000m
      volumeMounts:
        - name: containers
          path: /home/user/.local/share/containers
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475 

  - name: containers
    volume:
      size: 100Gi

attributes:
  pod-overrides:
    metadata:
      labels:
        che-workspace: 'true'
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  che-workspace: 'true'
              topologyKey: kubernetes.io/hostname