# TODO: Automate this with Renvoate
FROM samanhappy/mcphub:latest

# TODO: Automate this with Renovate
RUN curl https://download.docker.com/linux/static/stable/x86_64/docker-28.3.3.tgz | tar -xz -C /usr/local/bin --ignore-command-error --strip-components=1 docker/docker
