name: ci

on:
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      # - name: Build and push
      #   id: idracexporter_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.3.0
      #   with:
      #     context: ./Images/iDRACExporter
      #     cache-from: type=registry,ref=kristianfjones/idracexporter-docker:core0
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/idracexporter-docker:core0

      - name: Build and push
        id: gobetween_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/GoBetween
          cache-from: type=registry,ref=kristianfjones/gobetween-docker:core0
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfjones/gobetween-docker:core0

      # - name: Build and push
      #   id: hyperglass_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.3.0
      #   with:
      #     context: ./Images/HyperGlass
      #     cache-from: type=registry,ref=kristianfjones/hyperglass-docker:core0
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/hyperglass-docker:core0

      - name: Build and push
        id: pgexporter_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/PGExporter
          cache-from: type=registry,ref=kristianfjones/pgexporter-docker:core0
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfjones/pgexporter-docker:core0

      - name: Build and push
        id: dns_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/CoreDNS
          cache-from: type=registry,ref=kristianfjones/coredns-docker:core0
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfjones/coredns-docker:core0

      - name: Build and push
        id: ipamnetbox_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/NetBox
          cache-from: type=registry,ref=kristianfoss/netbox:core
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfoss/netbox:core

      - name: Build and push
        id: keadhcp_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/Kea
          cache-from: type=registry,ref=kristianfjones/kea:vps1-core
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64,linux/riscv64
          push: true
          tags: kristianfjones/kea:vps1-core

      # - name: Build and push
      #   id: docker_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.3.0
      #   with:
      #     context: ./Images/Web
      #     cache-from: type=registry,ref=kristianfjones/caddy-core-docker:vps1
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/caddy-core-docker:vps1

      - name: Build and push
        id: mariadbd_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/MariaDB
          cache-from: type=registry,ref=kristianfjones/mariadb:vps1-core
          cache-to: type=inline
          push: true
          tags: kristianfjones/mariadb:vps1-core

      - name: Build and push
        id: keaadmin_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/KeaAdmin
          push: true
          tags: kristianfjones/kea:vps1-admin

      - name: Build and push
        id: asterisk_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./Images/Asterisk
          push: true
          tags: kristianfjones/asterisk-pbx:vps1

      # - name: Build and push
      #   id: enms_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.3.0
      #   with:
      #     context: ./Images/eNMS
      #     push: true
      #     tags: kristianfjones/enms:vps1