name: ci

on:
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and push
        id: openwebuimcpo_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/OpenWebUI
          file: Dockerfile.MCP
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfoss/openwebui:core-mcp

      - name: Build and push
        id: postfix_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/Postfix
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfoss/postfix:core

      - name: Build and push
        id: keadhcp_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/Kea
          cache-from: type=registry,ref=kristianfjones/kea:vps1-core
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: kristianfjones/kea:vps1-core

      - name: Build and push
        id: ipamnetbox_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/NetBox
          cache-from: type=registry,ref=kristianfoss/netbox:core
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfoss/netbox:core



      - name: Build and push
        id: openldap_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/LDAP
          cache-from: type=registry,ref=kristianfjones/library-openldap:latest
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: kristianfjones/library-openldap:latest

      - name: Build and push
        id: pgpool_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/PGPool
          cache-from: type=registry,ref=kristianfjones/pgpool:latest
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: kristianfjones/pgpool:latest

      # - name: Build and push
      #   id: idracexporter_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.1.1
      #   with:
      #     context: ./Images/iDRACExporter
      #     cache-from: type=registry,ref=kristianfjones/idracexporter-docker:core0
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/idracexporter-docker:core0

#      - name: Build and push
#        id: gobetween_build
#        if: ${{ github.ref == 'refs/heads/main' }}
#        uses: docker/build-push-action@v3.1.1
#        with:
##          context: ./Images/GoBetween
#          cache-from: type=registry,ref=kristianfjones/gobetween-docker:core0
#          cache-to: type=inline
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: kristianfjones/gobetween-docker:core0

      # - name: Build and push
      #   id: hyperglass_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.1.1
      #   with:
      #     context: ./Images/HyperGlass
      #     cache-from: type=registry,ref=kristianfjones/hyperglass-docker:core0
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/hyperglass-docker:core0

      - name: Build and push
        id: pgexporter_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/PGExporter
          cache-from: type=registry,ref=kristianfjones/pgexporter-docker:core0
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfjones/pgexporter-docker:core0

      - name: Build and push
        id: dns_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/CoreDNS
          cache-from: type=registry,ref=kristianfjones/coredns-docker:core0
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianfjones/coredns-docker:core0



      # - name: Build and push
      #   id: docker_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.1.1
      #   with:
      #     context: ./Images/Web
      #     cache-from: type=registry,ref=kristianfjones/caddy-core-docker:vps1
      #     cache-to: type=inline
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: kristianfjones/caddy-core-docker:vps1

#      - name: Build and push
#        id: mariadbd_build
#        if: ${{ github.ref == 'refs/heads/main' }}
#        uses: docker/build-push-action@v3.1.1
#        with:
#          context: ./Images/MariaDB
#          cache-from: type=registry,ref=kristianfjones/mariadb:vps1-core
#          cache-to: type=inline
#          push: true
#          tags: kristianfjones/mariadb:vps1-core

      - name: Build and push
        id: keaadmin_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/KeaAdmin
          push: true
          tags: kristianfjones/kea:vps1-admin

      - name: Build and push
        id: netboxdhcp_build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./Images/NetboxDHCP
          push: true
          tags: kristianfjones/netbox-dhcp:main

##      - name: Build and push
#        id: asterisk_build
#        if: ${{ github.ref == 'refs/heads/main' }}
#        uses: docker/build-push-action@v3.1.1
#        with:
#          context: ./Images/Asterisk
#          push: true
#          tags: kristianfjones/asterisk-pbx:vps1

      # - name: Build and push
      #   id: enms_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v3.1.1
      #   with:
      #     context: ./Images/eNMS
      #     push: true
      #     tags: kristianfjones/enms:vps1

      # - name: Build and push
      #   id: freeswitch_build
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: docker/build-push-action@v5.1.0
      #   with:
      #     context: ./Images/FreeSwitch
      #     cache-from: type=registry,ref=kristianfjones/freeswitch:latest
      #     cache-to: type=inline
      #     platforms: linux/amd64
      #     push: true
      #     tags: kristianfjones/freeswitch:latest